### ISSUE TITLE
Cannot access daily consumption - after Update to HA Core 2024.11.0

### ISSUE THREAD

**Issue by akicker** [DarwinsBuddy/WienerNetzeSmartmeter#268]
Logger: custom_components.wnsm.statistics_sensor
Quelle: custom_components/wnsm/statistics_sensor.py:129

Error retrieving data from smart meter api - Error: Cannot access daily consumption: {'Exception': 'API Gateway 10.15 encountered an error. Error Message: Resource /messdaten/1200626756/AT001000000000000000100000xxxxx/verbrauch not found. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - /messdaten/{kundennummer}/{zaehlpunkt}/verbrauch, Invocation Time:8:51:35 AM, Date:Nov 8, 2024, Client IP - 213.240.70.19, User - Default and Application:null'}
Error retrieving data from smart meter api - Error: Cannot access daily consumption: {'Exception': 'API Gateway 10.15 encountered an error. Error Message: Resource /messdaten/1200626756/AT00100000000000000010000yyyyy/verbrauch not found. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - /messdaten/{kundennummer}/{zaehlpunkt}/verbrauch, Invocation Time:8:51:35 AM, Date:Nov 8, 2024, Client IP - 213.240.70.19, User - Default and Application:null'}

**Comment by papedo79** [comment]
i have the complete same problem. no new data since 06-nov-2024

Error retrieving data from smart meter api - Error: Cannot access daily consumption: {'Exception': 'API Gateway 10.15 encountered an error. Error Message: Resource /messdaten/XXXXXXX/AT00100000000000000010000XXXXXXX/verbrauch not found. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - /messdaten/{kundennummer}/{zaehlpunkt}/verbrauch, Invocation Time:8:09:33 AM, Date:Nov 8, 2024, Client IP - 89.144.195.81, User - Default and Application:null'}
Traceback (most recent call last):
  File "/config/custom_components/wnsm/statistics_sensor.py", line 129, in async_update
    await self._import_statistics(smartmeter, start, _sum)
  File "/config/custom_components/wnsm/statistics_sensor.py", line 261, in _import_statistics
    consumption = await self.get_consumption(smartmeter, start)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/base_sensor.py", line 125, in get_consumption
    raise RuntimeError(f"Cannot access daily consumption: {response}")
RuntimeError: Cannot access daily consumption: {'Exception': 'API Gateway 10.15 encountered an error. Error Message: Resource /messdaten/XXXXXXXX/AT00100000000000000010000XXXXXXX/verbrauch not found. Request Details: Service - WN_SMART_METER_PORTAL_API_B2C, Operation - /messdaten/{kundennummer}/{zaehlpunkt}/verbrauch, Invocation Time:8:09:33 AM, Date:Nov 8, 2024,  Client IP - 89.144.195.81, User - Default and Application:null'}

**Comment by DarwinsBuddy** [comment]
I started to stwitch out /verbrauch for /bewegungsdaten, though the statistics sensor is not working any longer as I got something wrong with the granularity param. If someone wants to take a look in the meantime, feel free to contribute. I'll probably come to it later this weekend

**Comment by tschoerk** [comment]
> I started to stwitch out /verbrauch for /bewegungsdaten, though the statistics sensor is not working any longer as I got something wrong with the granularity param. If someone wants to take a look in the meantime, feel free to contribute. I'll probably come to it later this weekend

Fixed some variable naming (e.g. old verbrauch returned "value", bewegungsdaten returns "wert"). Works for me again now!

**Comment by wceleda** [comment]
same here, no updates since 5.11.24

**Comment by tschoerk** [comment]
> > I started to stwitch out /verbrauch for /bewegungsdaten, though the statistics sensor is not working any longer as I got something wrong with the granularity param. If someone wants to take a look in the meantime, feel free to contribute. I'll probably come to it later this weekend
> 
> Fixed some variable naming (e.g. old verbrauch returned "value", bewegungsdaten returns "wert"). Works for me again now!

The first import works and it fetches data properly, but after letting it sit for one day, there still a couple of problems with updating:

```
Warning
Logger: custom_components.wnsm.statistics_sensor
Quelle: custom_components/wnsm/statistics_sensor.py:295
Integration: WienerNetzeSmartmeter ([Dokumentation](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter), [Probleme](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues))
Erstmals aufgetreten: 00:42:00 (28 Vorkommnisse)
Zuletzt protokolliert: 13:42:01
Timestamp from API (2024-11-07 00:00:00+00:00) is less than previously collected timestamp (2024-11-07 23:00:00+00:00), ignoring value!

```
```
Error
Logger: custom_components.wnsm.statistics_sensor
Quelle: custom_components/wnsm/statistics_sensor.py:291
Integration: WienerNetzeSmartmeter ([Dokumentation](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter), [Probleme](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/issues))
Erstmals aufgetreten: 00:42:00 (28 Vorkommnisse)
Zuletzt protokolliert: 13:42:01
Minute of zeitpunktVon is non-zero: 2024-11-07 00:15:00+00:00. This must not happen! Has the API changed?
```

Was the old verbrauch call only returning hourly updates? I don't even know if its even possible to only receive 1 hour consumptions updates with the API changes.

**Comment by DarwinsBuddy** [comment]
I'm trying to figure this out since I started the branch. Maybe something that @reox can answer or fix?

**Comment by DarwinsBuddy** [comment]
I added some logging and got this on my local dev setup (which was last time updated in October)

for `/bewegungsdaten`

query params:
```
{
 'aggregat': 'NONE',
 'geschaeftspartner': '1202198861',
 'rolle': 'V002',
 'zaehlpunktnummer': 'AT0010000000000000001000015327605',
 'zeitpunktBis': '2024-11-09T23:59:59.999Z',
 'zeitpunktVon': '2024-10-31T00:00:00.000Z'
 }
```
the first 5 values of the returned `values` jsonarray:
```
[{'geschaetzt': False,
  'wert': 0.029,
  'zeitpunktBis': '2024-10-31T00:15:00Z',
  'zeitpunktVon': '2024-10-31T00:00:00Z'},
 {'geschaetzt': False,
  'wert': 0.041,
  'zeitpunktBis': '2024-10-31T00:30:00Z',
  'zeitpunktVon': '2024-10-31T00:15:00Z'},
 {'geschaetzt': False,
  'wert': 0.03,
  'zeitpunktBis': '2024-10-31T00:45:00Z',
  'zeitpunktVon': '2024-10-31T00:30:00Z'},
 {'geschaetzt': False,
  'wert': 0.026,
  'zeitpunktBis': '2024-10-31T01:00:00Z',
  'zeitpunktVon': '2024-10-31T00:45:00Z'},
 {'geschaetzt': False,
  'wert': 0.039,
  'zeitpunktBis': '2024-10-31T01:15:00Z',
  'zeitpunktVon': '2024-10-31T01:00:00Z'}]
```

It seems that my local setup has a state, s.t. the last data is from some day at `22:00:00Z` (I guess still summer time) and now we would be at `23:00:00Z` the same date, which would be `00:00+01:00` since we are in CET and not CEDT any longer.

So I guess this has something to do with time shift.

@reox can we make this resilient against that?

(or is my hypothesis potentially wrong?)

**Comment by DarwinsBuddy** [comment]
I made a PR, but I'm not sure about it. The API is currently not responding anything, so I guess something's broken on WienerNetze's side.

If someone can try it out maybe in the next days, I'd much appreciate some feedback

**Comment by W-M-B** [comment]
> I added some logging and got this on my local dev setup (which was last time updated in October)
> 
> for `/bewegungsdaten`
> 
> query params:
> 
> ```
> {
>  'aggregat': 'NONE',
>  'geschaeftspartner': '1202198861',
>  'rolle': 'V002',
>  'zaehlpunktnummer': 'AT0010000000000000001000015327605',
>  'zeitpunktBis': '2024-11-09T23:59:59.999Z',
>  'zeitpunktVon': '2024-10-31T00:00:00.000Z'
>  }
> ```
> 
> the first 5 values of the returned `values` jsonarray:
> 
> ```
> [{'geschaetzt': False,
>   'wert': 0.029,
>   'zeitpunktBis': '2024-10-31T00:15:00Z',
>   'zeitpunktVon': '2024-10-31T00:00:00Z'},
>  {'geschaetzt': False,
>   'wert': 0.041,
>   'zeitpunktBis': '2024-10-31T00:30:00Z',
>   'zeitpunktVon': '2024-10-31T00:15:00Z'},
>  {'geschaetzt': False,
>   'wert': 0.03,
>   'zeitpunktBis': '2024-10-31T00:45:00Z',
>   'zeitpunktVon': '2024-10-31T00:30:00Z'},
>  {'geschaetzt': False,
>   'wert': 0.026,
>   'zeitpunktBis': '2024-10-31T01:00:00Z',
>   'zeitpunktVon': '2024-10-31T00:45:00Z'},
>  {'geschaetzt': False,
>   'wert': 0.039,
>   'zeitpunktBis': '2024-10-31T01:15:00Z',
>   'zeitpunktVon': '2024-10-31T01:00:00Z'}]
> ```
> 
> start: `2024-10-25 22:00:00+00:00`
> 
> error:
> 
> ```
> homeassistant.exceptions.HomeAssistantError: Invalid timestamp: timestamps must be from the top of the hour (minutes and seconds = 0)
> ```
> 
> It seems that my local setup has a state, s.t. the last data is from some day at `22:00:00Z` (I guess still summer time) and now we would be at `23:00:00Z` the same date, which would be `00:00+01:00` since we are in CET and not CEDT any longer.
> 
> So I guess this has something to do with time shift.
> 
> @reox can we make this resilient against that?
> 
> (or is my hypothesis potentially wrong?)

hi, I have some business experience with Wiener Netze (but some time back):
the data should come using UTC timing... for us in Summer CEST is UTC+1 = the day ends at 23:00 
now we are in CET and the night ends at 22:00 
this is consistent with your observation, that the smartmeters observe UTC timing.

**Comment by DarwinsBuddy** [comment]
thank you so much @W-M-B this saves us time for RCA. :)

Let's try to make this resilient against time switch

So as you said there is the base case of standard time and two edge cases:

1. switch to summertime day (where we have 25 hours on sunday)
this will happen next on 30.03.2025, which means when querying on 01.04. we would get meter readings and movement data up to 30.03.2025 23:00, which is in fact 01.04.2025 00:00

2. switch to wintertime day (where one hour is cut)
this happened on 27.10.2024, which means when querying on 28.10. we would get meter readings and movement data up to 27.10.2024 22:00, which is in fact 28.10.2024 00:00

Furthermore, @reox the respective data put into recorder will have the last "end's timestamp" not at day x 00:00, but on these ocassions day x-1 22:00 or day x-1 23:00 resp. I guess?

@W-M-B is this correct or did I make a mistake?

**Comment by DarwinsBuddy** [comment]
I think I got it now.

I changed the API query for bewegungsdaten to querying for the exact last timestamp reported (in case of timeshift)
When I changed from `/verbrauch` to `/bewegungsdaten` I faced the issue that if the user has a quarter-hourly optin, there is no way to query for hourly data, which is needed for home assistant's recorder feature to take it in.
So in that case I aggregate the quarter-hourly data to hourly data in an idempotent function.
Since I cannot test this properly with live data, I'd appreciate if someone could test it with data from a zaehlpunkt without quarter-hourly reporting.

@reox @tschoerk as always feedback very much welcome. I'd not roll this right now, as I'd like to have at least one of you reviewing and approving the change.

**Comment by reox** [comment]
Thanks @DarwinsBuddy to look into this!

> Was the old verbrauch call only returning hourly updates? I don't even know if its even possible to only receive 1 hour consumptions updates with the API changes.

no it could do 1h or 15min. I decided to use the 1h back then, as I was not able to put 15min stats into HA...

> Furthermore, @reox the respective data put into recorder will have the last "end's timestamp" not at day x 00:00, but on these ocassions day x-1 22:00 or day x-1 23:00 resp. I guess?

We had this summer time discussion already :D I believe it does not matter, as time is in UTC anyways (and has to be given in UTC to HA).
These warnings you see are because (at least at the time when I wrote the statistics import) it was not possible to import anything else than at xx:00:00

> @reox @tschoerk as always feedback very much welcome. I'd not roll this right now, as I'd like to have at least one of you reviewing and approving the change.

I had a look at the code and it looks good. I'll run the code on my instance now!

**Comment by reox** [comment]
Well, first error I get is:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
    await self.async_update()
  File "/config/custom_components/wnsm/statistics_sensor.py", line 129, in async_update
    await self._import_statistics(smartmeter, start, _sum)
  File "/config/custom_components/wnsm/statistics_sensor.py", line 333, in _import_statistics
    total_usage += usage
TypeError: unsupported operand type(s) for +=: 'decimal.Decimal' and 'float'
```

**Comment by reox** [comment]
I removed the check in client.py in line 512 and it imports now, but I have the issue again where at midnight you get a huge spike in consumption:

![grafik](https://github.com/user-attachments/assets/003bcc93-bd58-40e2-863f-cfa93b76955d)

Not sure if there is some remnants of data...

**Comment by DarwinsBuddy** [comment]
I fixed the type mismatch.
I don't know if this spike is not from some faulty import beforehand.

Can you check by removing all of your data (i.e. resetting) and re-import?
I can not reproduce this behaviour :/

**Comment by tschoerk** [comment]
> Fixed the one above, but now I get:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _async_add_entity
>     await entity.async_device_update(warning=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1302, in async_device_update
>     await self.async_update()
>   File "/config/custom_components/wnsm/statistics_sensor.py", line 129, in async_update
>     await self._import_statistics(smartmeter, start, _sum)
>   File "/config/custom_components/wnsm/statistics_sensor.py", line 281, in _import_statistics
>     bewegungsdaten = await self.get_bewegungsdaten(smartmeter, start)
>                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/wnsm/base_sensor.py", line 169, in get_bewegungsdaten
>     response = await self.hass.async_add_executor_job(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/wnsm/api/client.py", line 512, in bewegungsdaten
>     raise SmartmeterQueryError("Historical data is empty")
> custom_components.wnsm.api.errors.SmartmeterQueryError: Historical data is empty
> ```
> 
> But it looks like this is not really an error, but there is just no data available for the time range. I see that the values before that were fetched from the API, but due to this error, none of the fetched data is imported.

This issue is likely caused by WienerNetze not updating their data exactly at midnight, but usually between 3 and 4 AM. As a result, for a few hours after midnight, the API returns empty data because the request uses a timestamp for the new date. This leads to multiple errors each day. So I agree with you, since the data validation is handled in the statistics_sensor anyway those line should probably be removed:
https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/blob/f5aa4fb1ad42d4299ff85185711ec25d8870b5d9/custom_components/wnsm/api/client.py#L511-L512

**Comment by DarwinsBuddy** [comment]
fixed it

**Comment by wceleda** [comment]
> fixed it

what should we do? is there an update available?

**Comment by W-M-B** [comment]
> thank you so much @W-M-B this saves us time for RCA. :)
> 
> Let's try to make this resilient against time switch
> 
> So as you said there is the base case of standard time and two edge cases:
> 
>     1. switch to summertime day (where we have 25 hours on sunday)
>        this will happen next on 30.03.2025, which means when querying on 01.04. we would get meter readings and movement data up to 30.03.2025 23:00, which is in fact 01.04.2025 00:00
> 
>     2. switch to wintertime day (where one hour is cut)
>        this happened on 27.10.2024, which means when querying on 28.10. we would get meter readings and movement data up to 27.10.2024 22:00, which is in fact 28.10.2024 00:00
> 
> 
> Furthermore, @reox the respective data put into recorder will have the last "end's timestamp" not at day x 00:00, but on these ocassions day x-1 22:00 or day x-1 23:00 resp. I guess?
> 
> @W-M-B is this correct or did I make a mistake?

I will look into this later this week, sorry I am a little busy these days.

**Comment by tschoerk** [comment]
> > fixed it
> 
> what should we do? is there an update available?

It's still being worked on and tested. 
You can update manually via this branch [https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/tree/f/api-fix](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/tree/f/api-fix) and try if it works for you.

**Comment by akicker** [comment]
+1 huge midnight spike Grid In Statistics

**Comment by papedo79** [comment]
> +1 huge midnight spike Grid In Statistics

for yesterdays data, the spike is gone.

**Comment by reox** [comment]
I think it may be an issue only for the first import... Subsequent imports seem to be fine. Not sure what is going on though.

**Comment by DarwinsBuddy** [comment]
I cannot reproduce this at all. not even when starting out from a fresh import :/

@papedo79 Did you purge the sensor's data before installing the integration anew?
