### ISSUE TITLE
Username/password invalid with log.wien credentials

### ISSUE THREAD

**Issue by benane** [DarwinsBuddy/WienerNetzeSmartmeter#281]
Hi, I am using log.wien to access my smart meter portal. But my log.wien credentials are not recognised by the integration and are shown as "Username/password invalid". Any way I can still use this integration?

**Comment by psinger** [comment]
same here

**Comment by W-M-B** [comment]
also have the issue. Last successfull data import was Tuesday.

**Comment by HuboSky** [comment]
Same here, it's not possible to connect with my credentials, which are working on the smartmeter portal. 
Any Tips what i could do?

**Comment by tschoerk** [comment]
So it seems the login process changed a bit.

To give some background, the steps for the current login are as follows:
1. Load login page via GET `https://log.wien/auth/realms/logwien/protocol/openid-connect/auth?client_id=wn-smartmeter&redirect_uri=https://smartmeter-web.wienernetze.at/&response_mode=fragment&response_type=code&scope=openid&nonce`
2. Return the action URL from the login form.
3. Send a POST to the URL from the login form with the keys username and password in the body
4. After a succesful login, the header of the response has the key `location` which is an URL in the format `https://smartmeter-web.wienernetze.at/#session_state=XXX&iss=XXX&code=XXX`
5. The code part of the URL is then used to request the tokens to access the full API

What seemed to change is that username and password are sent in two different steps, so the following steps seem to work:
1. Load login page via GET `https://log.wien/auth/realms/logwien/protocol/openid-connect/auth?client_id=wn-smartmeter&redirect_uri=https://smartmeter-web.wienernetze.at/&response_mode=fragment&response_type=code&scope=openid&nonce`
2. Return the action URL from the login form.
3. Send a POST to the URL from the login form with the keys username and login set to "" in the body
4. Return the action URL from the login form.
5. Send a POST to the URL from the login form with the keys username and password in the body
6. After a succesful login, the header of the response has the key `location` which is an URL in the format `https://smartmeter-web.wienernetze.at/#session_state=XXX&iss=XXX&code=XXX`
7. The code part of the URL is then used to request the tokens to access the full API

You can manually update the client.py with the changes found [here](https://github.com/tschoerk/WienerNetzeSmartmeter/commit/8dfc3fbf281c4430c0765a9692048784c5d96949). Still need to update tests before opening a PR.

What I noticed though that I got a captcha response once after the second form. This was a couple hours ago and haven't seen it since, but this is something which could happen in the future and will probably make our lives harder.

**Comment by elmartinoAT** [comment]
same here ... stopped since yesterday ...
updated the [client.py](https://github.com/tschoerk/WienerNetzeSmartmeter/commit/8dfc3fbf281c4430c0765a9692048784c5d96949), also no login possible

**Comment by NightDragon1** [comment]
Same

**Comment by wceleda** [comment]
same here:
File "/config/custom_components/wnsm/api/client.py", line 128, in login
    code = self.credentials_login(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wnsm/api/client.py", line 78, in credentials_login
    raise SmartmeterLoginError("Login failed. Check username/password.")
custom_components.wnsm.api.errors.SmartmeterLoginError: Login failed. Check username/password.

will there an updated version of wsnm?

**Comment by elmartinoAT** [comment]
It works with the changes in client.py from [here](https://github.com/tschoerk/WienerNetzeSmartmeter/commit/8dfc3fbf281c4430c0765a9692048784c5d96949)
but i had also to implement the changes in constants.py from [here](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/commit/119ba21158004ac90daeaf99b375a0358a0dfea1)

But now i have to add and login 3 times separately for each of my 3 entities

**Comment by wceleda** [comment]
> It works with the changes in client.py from [here](https://github.com/tschoerk/WienerNetzeSmartmeter/commit/8dfc3fbf281c4430c0765a9692048784c5d96949) but i had also to implement the changes in constants.py from [here] ([119ba21](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/commit/119ba21158004ac90daeaf99b375a0358a0dfea1)) (otherwise error 'Anlagentypen' in client.py)
> 
> But now i have to add and login 3 times separately for each of my 3 entities

after updating client.py and constants.py as mentioned before used energy and used solar energy are visible but not the amount of solar energy that was fed into the grid

**Comment by HuboSky** [comment]
I started with Home Assistant a few days ago and i'm learning a lot in the last days, but troubleshooting like this ist to much at the moment. So, could someone help me to solve my problem? I couldn't add the integration cause of the login error.
So, what should i do? Also, change the client.p? But how, i'm afraid to make a big mistake there. 
I hope there is somebody which could help me in german? This would be easier for me.

**Comment by elmartinoAT** [comment]
> I started with Home Assistant a few days ago and i'm learning a lot in the last days, but troubleshooting like this ist to much at the moment. So, could someone help me to solve my problem? I couldn't add the integration cause of the login error. So, what should i do? Also, change the client.p? But how, i'm afraid to make a big mistake there. I hope there is somebody which could help me in german? This would be easier for me.

Wait for the next release

**Comment by tschoerk** [comment]
> It works with the changes in client.py from [here](https://github.com/tschoerk/WienerNetzeSmartmeter/commit/8dfc3fbf281c4430c0765a9692048784c5d96949) but i had also to implement the changes in constants.py from here ([119ba21](https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/commit/119ba21158004ac90daeaf99b375a0358a0dfea1)) (otherwise error 'Anlagentypen' in client.py)
> 
> But now i have to add and login 3 times separately for each of my 3 entities

Ah thanks for the hint, yeah there was already another bugfix implemented in main, which changed the name of a variable.

We will try our best to get a decently working version out asap. Improvements of speed, etc. can be done afterwards.

**Comment by DarwinsBuddy** [comment]
I'm currently fixing it.

I also reached out to WienerNetze regarding this flaky login. Maybe we could get a direct authentication integration via the portal in the long run. Let's see.

**Comment by DarwinsBuddy** [comment]
I'm going to release this ASAP

Thank you all involved in the RCA.
Special thanks to @mat-333 for the reference

**Comment by DarwinsBuddy** [comment]
I'll furthermore try to resolve this potentially with an official integration with Wiener Netze. Wish me luck :crossed_fingers:

**Comment by HuboSky** [comment]
It works!! Thanks a lot!!!
