### ISSUE TITLE
Consumption and Energy usage

### ISSUE THREAD

**Issue by gluckb** [DarwinsBuddy/WienerNetzeSmartmeter#4]
Hi DarwinsBuddy,

thank you for this great integration and for your effort.

I have a problem with the values I got. According to the integration the consumption was 9.822 kWh yesterday.
However the Smart Meter Webportal shows me 9.381 kWh. Previously I was also using the Vienna Smart Meter integration and there was always a gap between the values. What could be the reason for this difference?

My other question is related to the energy usage dashboard. I see either negative values or small differences between consumption of the day before yesterday and yesterday. As far as I understood SensorStateClass.TOTAL_INCREASING is meant for energy meters showing totals.
E.g.
Monday: meter shows: 10.000 kWh, daily usage: 10.000 kWh
Tuesday: meter shows: 15.000 kWh, daily usage: 5.000 kWh
The increasing value is the total consumption, the daily usage is the difference between those two values. A decreasing value means a new meter cylce. Since we already get daily consumption from the Smart Meter Webportal, this sensor class seems to be the wrong approach.

Honestly, I did not found a suitable state class for this scenario in the developer documentation. https://developers.home-assistant.io/docs/core/entity/sensor/

What is your experience?

**Comment by DarwinsBuddy** [comment]
Hi and thanks :)

The gap appears to be, because I've not yet understood how Wiener Netze are fetching their data.
That's what I know so far:

- if you opt-in to 15-minutes interval measurement, you get daily usage to a granularity of 15 minutes
- the data from your smart meter apparently gets fetched by WN only a few times a day (exact times not known)
- when they fetch data, somehow a few measurements are always missing (I try to circumvent this, see below)
- sometimes they miss fetch anything

The workaround for me was interpolating the missing measurements with the avg provided by the API, see https://github.com/DarwinsBuddy/WienerNetzeSmartmeter/blob/e2927dab748a6134b21d5767aaf92c289d3d26dd/custom_components/wnsm/sensor.py#L167

Imho you're absolutely correct with your assumptions towards the total increasing sensor afaik.

Nevertheless, my ideal case of how this sensor should work is as follows.

- regularly poll the API and try to fetch the data
- do not just add the "total meter readings of the day" (guesstimated or not), but store the quarterly (or hourly) once exactly as they appear

i.e.
NOT once a day at ~2am get a huge load of consumption
BUT once a day you get the "history" of the last day into your home assistant

Unfortunately I've not found the right way to to this with HA, since I was only capable of updating the sensor at exactly *one* point in time (namely the point in time, when I am reading the new meter values), but in one update cycle update the whole last day with individual values per 15minutes/1hour.

If you have any knowledge about how this could work, or if you're having any other idea how we could improve this, I'd very much appreciate it.

**Comment by DarwinsBuddy** [comment]
see #8

**Comment by financelurker** [comment]
ah... ` # TODO: find out how to use quarterly data in another sensor ` is this the reason why I won't get the 15m-breakdown of usage imported? (I have enabled it in the wienernetze web-frontend, but in HA I only see one column of usage per day)

**Comment by DarwinsBuddy** [comment]
@financelurker yes. unfortunately that's it. I've to figure out how this could work in home-assistant. I am also eager to get that information into hassio as well. If you have any input on that, please let me know. :)

**Comment by Ing-Med** [comment]
its too technical for me, but maybe there's a solution here somewhere: https://community.home-assistant.io/t/import-old-energy-readings-for-use-in-energy-dashboard/341406/20

Wien Energie seems to be the worst. I checked on my sensor today and it seemed that it imported 2 days into one because apparently wien energie was not able to provide the data quickly enough (as in 1 whole day), so your integration did just add it to the next day.
Nothing you can do on your end to stop this unless historic data will be accepted for the energy grid sensors. 


in the meantime i might look into forking your python script to feed the scraped data into an influxdb on the quarterly basis. When HA is ready for imports, it should then be easy to pull the data and import it into the engergy sensors.
