### ISSUE TITLE
Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by hondo78** [DarwinsBuddy/WienerNetzeSmartmeter#47]
Hello,

I have reinstalled my Home Assistant last week.  With the old installation the reading of the SmartMeter worked. 

Now when setting it up I get the following error:
"The configuration flow could not be loaded: {"message": "Invalid handler specified"} "

Can this possibly be related to the Python version (3.10.1)?

Kind Regards

Maik

**Comment by DarwinsBuddy** [comment]
Hi Maik,

this seems to be a rather common problem.
https://community.home-assistant.io/t/error-adding-integration/485237/14

Since I am not able to reproduce the issue, it's hard for me to even start
off somewhere.
My assumption though is, that something with your HomeAssistant
installation is not right.

Yes, the wnsm integration uses python3.
If you are on a lower major version this could be the issue. (but then also
home assistant in general could be having troubles I guess).

**Comment by DarwinsBuddy** [comment]
As it's presumably not related to this integration, I suggest you ask here: https://community.home-assistant.io/ if above link doesn't solve your issue.

**Comment by hondo78** [comment]
Hi,
I was now able to get it to work. The cause was probably the update to Python3.10.
I could solve it by an update of pip3 reinstall from Homeasisstant.

Thanks for the quick reply :)
