### ISSUE TITLE
Power consumption shows minus value

### ISSUE THREAD

**Issue by stefanschramek** [DarwinsBuddy/WienerNetzeSmartmeter#55]
Hi,
as the integration stopped working some days ago I realized there was a newer version available.
After the latest update it shows a high minus value "-3.164,95 kWh" for this day.
Do you have an idea why this is happening and how to solve this?
Is there a way to start from scratch? I tried to remove the integration and add it again but the value is still there.
Thanks in advance!

**Comment by DarwinsBuddy** [comment]
Hi

Try removing the entity first https://community.home-assistant.io/t/how-to-remove-unavailable-entities/179075/2

then reinstall the integration.


If that doesn't help, please double check the information provided on the Smart meter website and figure out if the negative value is shown there as well or if it differs.

If the data provided returned by the API is negative we cannot compensate for that.

Also: Currently the sensor is measuring merely your "Zählerstand". So basically the current count of kWh. When you don't pull your data regularly, it could be that you're getting reportedly high meter readings for that they, although it is the cumulative sum of the consumption of days since your last sensor update.

@reox is working on a more granular and robust update, which should overcome this issue.

To be always up to date install this integration via HACS and regularly check for updates. we even switched to semantic versioning lately thanks to @TheRealVira 

Get back to us anytime.

Cheers :)

**Comment by stefanschramek** [comment]
Hi,

thank you for the quick reply.
Actually after removing the integration the entity seems to be also removed - there is no entity left for this.

This was the last correctly set value - after this it stopped and I realized some days after
<img width="875" alt="17-01-2023_ok" src="https://user-images.githubusercontent.com/921342/222405937-6a580077-dc41-4a56-88e8-bc14fd7115f6.png">
Here you can see the wrong value
<img width="910" alt="22-02-2023_wrong" src="https://user-images.githubusercontent.com/921342/222406779-db9f365a-e35a-4af8-b84f-e6f34b7bb686.png">
This is a view from the values as the are shown in the web interface - the minus value is not reflected there
<img width="723" alt="01-2023_web" src="https://user-images.githubusercontent.com/921342/222406322-04c46b7f-62bc-4c94-9cfa-a0d8244dd237.png">
<img width="683" alt="02-2023_web" src="https://user-images.githubusercontent.com/921342/222406362-db7967c0-7b12-4c48-83a8-f29cd5a3a984.png">
Do you know a way to reset this data completely and to start from scratch?
Thanks
Stefan

**Comment by reox** [comment]
I believe you have to delete the statistics as well. Goto Developertools -> Statistics -> Search for the zählpunkt and delete it.

**Comment by stefanschramek** [comment]
> I believe you have to delete the statistics as well. Goto Developertools -> Statistics -> Search for the zählpunkt and delete it.

Thanks! This worked like a charm!

**Comment by DarwinsBuddy** [comment]
closing this . thanks @reox for your help
