### ISSUE TITLE
No updates for several days

### ISSUE THREAD

**Issue by mundschenk-at** [DarwinsBuddy/WienerNetzeSmartmeter#77]
Looks like the API changed again. I haven't had any sensor updates since last Friday and when I enabled debug logging for the integration, I get this in the logs:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 747, in async_device_update
    await task
  File "/config/custom_components/wnsm/sensor.py", line 244, in async_update
    zaehlpunkt = await self.get_zaehlpunkt(smartmeter)
  File "/config/custom_components/wnsm/sensor.py", line 150, in get_zaehlpunkt
    z for z in zps[0]["zaehlpunkte"] if z["zaehlpunktnummer"] == self.zaehlpunkt
KeyError: 0
```

**Comment by mr-p666** [comment]
No, it isn't the API. They have a complete failure of the smart meter interface since Thursday. You can also see this, when you take a look at the smartmeter-web.wienernetze.at site.
I called them today and they confirmed this outage. They couldn't tell me - what a surprise - until when it will work again. ;-)
But in the evening hours I was able to discover some data from the end of last week in the web interface. So something is happening... albeit in small steps.

**Comment by mundschenk-at** [comment]
Oh my, that sounds like a mess. 🫣

**Comment by DarwinsBuddy** [comment]
Thanks a lot @mundschenk-at for reporting
and @mr-p666 for investigating. That saves myself some time. Unfortunately the integration is, still, just reactive upon such incidents.

I'll have to invest some time to look at @reox PR regarding statistical measurements, which may compensate for such outages in some way.

Stay safe and thanks for the combined effort.

**Comment by reox** [comment]
I can report that the API seems to be back again with data. However, I lost the 17th of March...
The problem with the current approach is, that as soon as data is imported from timepoint `t`, it seems to be impossible to add any data for `x < t`. 
I.e., in the current case: The outage started on the 17th and was resolved on the 20th. However, for some reason data for the 18th appeared first and thus the 17th is now lost forever...
As far as I can tell, HA is not able to add stuff in between, because the overall sum has to match.
Or am I wrong about that? (Unfortunately, there is no documentation on the functions :( )

**Comment by mr-p666** [comment]
Even if there was no new data, rows were created in the statistics table over time.
Currently the only way to add the missing data is to manually update the corresponding lines in the DB. Basically, this is quite easy if you are familiar with SQL queries.

**Comment by reox** [comment]
as far as I remember from the thread in the HA community forum, SQL is only half the way. That's why there is the statistics import in the first place. But also that one is limited in many regards... As far as I can tell, HA is not built to support that and thus there are now so many workarounds.

Or can you nowadays simply add the required data via SQL and all the statistics and so on will work correctly?

**Comment by reox** [comment]
I see. Then the question is, if I should implement it :D I guess using the API with the known limitations is much safer, but knowing a workaround is also good!
